### ISSUE TITLE
minori tools problems

### ISSUE THREAD

**Issue by Ryusei1** [Inori/FuckGalEngine#21]
Hello, may you help me with something? I'm having trouble compiling the tool, but i don't have idea where is the error

Here's the error

2>translate.cpp
2>c:\users\arata\downloads\fuckgalengine-master\minori\minori\minoripatch\translate.cpp(195): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
2>tools.cpp
2>c:\users\arata\downloads\fuckgalengine-master\minori\minori\minoripatch\tools.cpp(144): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
2>scriptparser.cpp
2>c:\users\arata\downloads\fuckgalengine-master\minori\minori\minoripatch\scriptparser.cpp(201): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
2>MinoriPatch.cpp
2>c:\users\arata\downloads\fuckgalengine-master\minori\minori\minoripatch\minoripatch.cpp(708): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?

**Comment by Aleisster** [comment]
your visual studio is too outdated

**Comment by Inori** [comment]
I'm not sure if this problem is VS version related. 
If you just want to unpack the game's paz files, then `MinoriPatch` is not necessary, you just need to compile `fuckpaz` or you can download it directly from [here](https://bbs.sumisora.net/read.php?tid=11076153)

**Comment by Ryusei1** [comment]
Specifically, I'm trying to extract, translate and repack the scripts

**Comment by Inori** [comment]
The  Debug Build property is not configured correctly, switch to Release Build can solve the problem.
The 'stdafx.h' problem is caused by precompiled headers missing, it's a common problem, try to google it first.

**Comment by Neroldy** [comment]
@Ryusei1 
Well, use this project sln file directly seems not to be good method, because these code project files are not well defined, some library path are configured using author's absolute path. I think a better way is to create your own project and only add these code files and configure your library path.

**Comment by Inori** [comment]
@Ryusei1 @Neroldy  
Fixed, use relative path, both Debug and Release build. Should be okay on other computers.

Note I'm using VS2017, to compile using another VS verison,  maybe you have to reconfigure the Windows SDK Version property.
