### ISSUE TITLE
fuckpaz problem

### ISSUE THREAD

**Issue by munpin2010** [Inori/FuckGalEngine#22]
Hello. I need to extract some scripts from Eden*, translate lines and repack them again. I managed to compile fuckpaz tool, but when I've tried using it to extract files, it just stopped working with a generic "Application has stopped working" error. By chance, is this tool not usable with MangaGamer's version of the game, or the problem lies elsewhere?

I've also failed to understand how can I repack the scripts when I'm done messing with them. I hope you can help me.

**Comment by Neroldy** [comment]
1. As we know, minori games use blowfish and rc4 for encryption and each game has different keys. Fuckpaz uses hard coded keys to decrypt resources. So maybe your game version's key is different from the fuckpaz's. The solution is using OD or x64dbg or other debugger to get the key.
2. For repacker, you also need to get the right keys we mentioned above, and add to the repacker's source if it didn't have your game's key.

**Comment by munpin2010** [comment]
Thanks for the reply. No, you see, I'm a total novice in this field and my programming experience is close to zero, so I guess the problem is out of my hands. I can still use the tool to unpack the original version of the vn, it will do for now.

My question about the repacker was also much more trivial: how do I use it at all? The instructions in the tool goes as such: "usage: fuckpaz.exe <input.paz> <game index> [output.paz]",  but I'm kinda confused: so, I have a number of .sc scripts, and I need to repack them in .paz again... How can I do it?

**Comment by Neroldy** [comment]
Well, in my memory, first, you need to put your original paz file in your modified sc files folder, and then type:
```
fuckpaz input.paz output.paz game_index
```
input.paz is your script paz filename, and output paz is your repack paz name such as cnscript.paz.
That's it.

**Comment by Inori** [comment]
As the usage says:
`usage: fuckpaz.exe <input.paz> <game index> [output.paz]`
you should use it this way, eg:
`fuckpaz input.paz 1 output.paz` 
if your game is original version of Eden*.
