### ISSUE TITLE
new PSB (Riddle Joker)

### ISSUE THREAD

**Issue by aKKiww** [Inori/FuckGalEngine#23]
Are you still working on this? Look like they use a new version of PSB format (version = 3)
Please update it ;(
Here the file https://drive.google.com/open?id=1FirN4KxxGUV6_46AYbbjPjzY8eOXhqmn
Thank you!

**Comment by Inori** [comment]
I'm not working on krkr engine anymore, maybe you could get more information [here](https://github.com/xmoeproject/KrkrExtract) and [here](https://github.com/number201724/psbfile).
