### ISSUE TITLE
Windows下编译无法成功

### ISSUE THREAD

**Issue by SettingDust** [Inori/FuckGalEngine#25]
ahdprc的工具我编译无法成功，始终报错
无法找到princess
然而princess存在

Windows 10 CodeBlocks TDM-GCC-64

之前没写过C++相关。。。 GCC 5.1.0

**Comment by sgqy** [comment]
编译时加参数 `-Ilib` 以添加头文件包含目录。
链接时加参数 `-Llib` 以添加链接库包含目录，并在命令的最末尾、系统库的前面加上 `-lprincess` 以正确链接。

CodeBlocks 的 GUI 应该有相应的设置。

**Comment by SettingDust** [comment]
好的 谢谢您。替换列表是什么格式呢？

**Comment by sgqy** [comment]
~~年代过于久远，我猜一下~~

因为有些字符（比如`♪`）在 936 里不存在，转换成 936 会变成`?`。
如果要显示这个符号，就要找个 936 里存在的换掉，比如用`＃`。
之后修改字体，把原本是`＃`的地方用`♪`的图形更换即可。

所以替换列表想怎么来都行，~~那句话应该只是随手一记~~
~~不过这引擎最好使用外挂式封装~~
