### ISSUE TITLE
minori - reverse engineering

### ISSUE THREAD

**Issue by imKota** [Inori/FuckGalEngine#29]
Hello!
Tell me, is it possible to somehow circumvent the limitations of characters in the text? Now that restriction is 27 characters, after which the line is cut off in the middle of the word, and transferred to a new line.

Here are examples
![1](https://user-images.githubusercontent.com/24241471/51940257-8e83c880-2422-11e9-9a3b-7d2a222b23b6.png)
![2](https://user-images.githubusercontent.com/24241471/51940260-8fb4f580-2422-11e9-8646-a8530a12ef91.png)
![3](https://user-images.githubusercontent.com/24241471/51940263-917eb900-2422-11e9-80b0-8f1a9bd6ee0e.png)

**Comment by imKota** [comment]
@Inori And could you please send me the compiled release of https://github.com/Inori/FuckGalEngine/tree/master/Minori/Minori ?

**Comment by TP-SafeHouse** [comment]
I haven't tried that. When I translate it into Chinese, I kept line limitations as it is. It's more beautiful, isn't it?

**Comment by Inori** [comment]
I haven't tried that. When I translate it into Chinese, I kept line limitations as it is. It's more beautiful, isn't it?

**Comment by imKota** [comment]
@Inori In Russian, the dictionary simply breaks off to the middle and is transferred. What is badly read.

For example, it is the **third screenshot**, the **second line** in English: 

`That is why I try my best, hoping that someday I will see a posit`
`ive result.`

Maybe somehow it is possible to increase the limit on the 5-8 characters? 
That would be just right.

**Comment by imKota** [comment]
@Inori And it would be nice if you adapted your work on the minori novels for translation into English.

**Comment by Inori** [comment]
Even if you can increase the limit, there will always be some words broken off. 
In your example, the word ```positive``` may be complete after increasing the limit, but the word ```result``` will be broken off at the same time. You can not determine which word will be at the end of line.
And the text will not be at the center of the game window, which makes it looking ugly.

My tools includes paz package extractor (fuckpaz) and game exe hooks (MinoriPatch), fuckpaz works no matter what language you are working on, and MinoriPatch support chinese which means it supports engligh theoretically. The only thing is that MinoriPatch has many hard code address which only aims to  the newest game of Minori (currently Trinoline). Besides if you want to translate a game completely, you may also have to modify the exe file.

**Comment by imKota** [comment]
@Inori I would be very grateful to you if you would help me with this.

**Comment by 0xh3LL0** [comment]
@imKota
or... you can browse through commit and revert the changes by yourself
https://github.com/Inori/FuckGalEngine/commit/666323e1c8283750477c729d8165cd2718cda552

**Comment by imKota** [comment]
@Inori Already tried, but at assembly errors take off.
If it's not difficult for you, could you adapt the current practices for 12 no Tsuki no Eve. Please

**Comment by imKota** [comment]
@0xh3LL0 Already tried, but at assembly errors take off.

**Comment by imKota** [comment]
@Inori I kind of figured out a bit. Compiled minoripatch.dll. and launched a Chinese patched launcher.
But he does not support the Russian language, but the original Japanese supports it. Here are the screenshots:

**chinese launcher**
![windows 7 2019-02-04 16-14-29](https://user-images.githubusercontent.com/24241471/52213032-fdd43f00-289e-11e9-86c4-c656621e7340.png)

**original japanese launcher**
![windows 7 2019-02-04 16-18-53](https://user-images.githubusercontent.com/24241471/52213083-1f352b00-289f-11e9-9b74-dd70b38f6e02.png)

I can not patch the original Japanese launcher, because I do not know how to use debager.
As for the minoripatch.dll itself, I can correct it to fit my needs.
Therefore, if you make AntiCDK + InstallPatch for **12 no Tsuki no Eve**, I will be grateful to you. 
Since I can deal with the rest: 3

**Comment by imKota** [comment]
@Inori, @AyanamiRei 
I know that you need to make changes to the source code.
https://github.com/Inori/FuckGalEngine/blob/b76ba865a636cadd8fe42be30a64419a945f9fb2/Minori/Minori/InstallPatch/InstallPatch.cpp#L188-L209

https://github.com/Inori/FuckGalEngine/blob/b76ba865a636cadd8fe42be30a64419a945f9fb2/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L167-L168
https://github.com/Inori/FuckGalEngine/blob/b76ba865a636cadd8fe42be30a64419a945f9fb2/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L245
https://github.com/Inori/FuckGalEngine/blob/b76ba865a636cadd8fe42be30a64419a945f9fb2/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L283
https://github.com/Inori/FuckGalEngine/blob/b76ba865a636cadd8fe42be30a64419a945f9fb2/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L546
https://github.com/Inori/FuckGalEngine/blob/b76ba865a636cadd8fe42be30a64419a945f9fb2/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L668

And also follow the instructions for patching.
But as I understand there is data for another novel.

I do not understand much about reverse engineering. Therefore, I ask for your help.
If you make AntiCDK + InstallPatch for **12 no Tsuki no Eve**. And tell me how to patch the EXE correctly, I will be very welcome to you.

Since I can deal with the rest: 3

**Comment by Inori** [comment]
1. You use [SetDll.exe](https://github.com/Inori/FuckGalEngine/blob/master/_general_tools/Setdll.exe) to modify the game exe file, then the game can load MinoriPatch.dll. 
Command like: `setdll /d:MinoriPatch.exe 12eve.exe`

2. For scripts, unpack `scr.paz` using `fuckpaz.exe`, you get a lot of `*.sc` files, then you use `sc_text_out.py` to extract the text into `txt` files.
After translated, you use `sc_text_in.py` to import the text back into `sc` files.
Finally, you use `fuckpaz.exe` again to pack the `sc` file into `paz` package.

3. For images, there are two types of images.

- a. Images in `sys.paz` is simple, you just unpack the `paz`, modify images, then repack.
- b. Images in 'bg.paz' is a little complicated. You have 3 ways to deal with it.

  i. Just give up, since there will be only a few images which have Japanese text, and there will be script which you can translate showing under the image when you play the game. I suggest you this way.
  ii. Just repack using 'fuckpaz.exe', this will make the repacked package very big, but it works.
  iii. Replace the only the image you modified. This will be a hard way. First you use `PackCnBg.py` to pack the modified images, you must keep the `png` format, include its' channel count. The packed file will be `cnbg.paz` but it's not a real `paz` format file. So the game can not parse it. You have to patch the game to make it works. Code is in `MinoriPatch.cpp`. You can use hard code address in commit which @0xh3LL0 provides. Just replace the address in the newest code with the ones in that commit should work.

4. I changed the repacked package name, plus `cn` prefix just for making the old Japanese game can work at the same time. If you do not care about it, just comment the code about hooking `CreateFileA`

5. There are some features in `MinoriPatch` which you may not want, like showing original Japanese once press Tab. Just comment the code.

**Comment by imKota** [comment]
@Inori Thanks for answering!

> 1. You use [SetDll.exe](https://github.com/Inori/FuckGalEngine/blob/master/_general_tools/Setdll.exe) to modify the game exe file, then the game can load MinoriPatch.dll.
   Command like: `setdll /d:MinoriPatch.exe 12eve.exe`

Now I will try, do as you wrote.

> 3. For images, there are two types of images.
>* b. Images in 'bg.paz' is a little complicated. You have 3 ways to deal with it.

I want to use the "b III.", but as I described above. For some reason, the created archive is simply not readable. As if it is simply not there (although it is).

This is rather strange considering that I am using your patch. It is received that it did not initially load yours  **cnbg.paz** 
Does he have to work?
![image](https://user-images.githubusercontent.com/24241471/52332851-d602e980-2a0c-11e9-95b7-6bb6a5c4ccad.png)

> 1. I changed the repacked package name, plus `cn` prefix just for making the old Japanese game can work at the same time. If you do not care about it, just comment the code about hooking `CreateFileA`

Yes I know. I understand the code.

> 2. There are some features in `MinoriPatch` which you may not want, like showing original Japanese once press Tab. Just comment the code.

Yes, I did not need me already removed

**Comment by imKota** [comment]
@Inori I’m also confused that your chbg.paz file paths go fine
**your chbg.paz**
![image](https://user-images.githubusercontent.com/24241471/52333210-b4eec880-2a0d-11e9-9d2c-98190381047d.png)

**my rubg.paz** 

cnbg/eve_telop_anzuchan.bmp
cnbg/eve_telop_K02_megasameta.bmp

![image](https://user-images.githubusercontent.com/24241471/52333360-1c0c7d00-2a0e-11e9-9e65-e21e0f0217e6.png)

**Comment by imKota** [comment]
@Inori Another question, sorry. 
In the committee that indicated @0xh3LL0 there are no addresses for the latest version of the patch.

https://github.com/Inori/FuckGalEngine/blob/b76ba865a636cadd8fe42be30a64419a945f9fb2/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L546
https://github.com/Inori/FuckGalEngine/blob/b76ba865a636cadd8fe42be30a64419a945f9fb2/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L668

How to deal with this?

**Comment by Inori** [comment]
Reusing my patch is a clever way, surprisingly you can find it!

You should have found than the file name format is different between yours and mine.
Do not append folder name before filename.
Just place modified bmp file in a folder named `cnbg`, then run `PackCnBg.py` outside of the folder.

**Comment by Inori** [comment]
> @Inori Another question, sorry.
> In the committee that indicated @0xh3LL0 there are no addresses for the latest version of the patch.
> 
> [FuckGalEngine/Minori/Minori/MinoriPatch/MinoriPatch.cpp](https://github.com/Inori/FuckGalEngine/blob/b76ba865a636cadd8fe42be30a64419a945f9fb2/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L546)
> 
> Line 546 in [b76ba86](/Inori/FuckGalEngine/commit/b76ba865a636cadd8fe42be30a64419a945f9fb2)
> 
>  void *pSavePngName = (void*)0x0046AC1C; 
> 
> [FuckGalEngine/Minori/Minori/MinoriPatch/MinoriPatch.cpp](https://github.com/Inori/FuckGalEngine/blob/b76ba865a636cadd8fe42be30a64419a945f9fb2/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L668)
> 
> Line 668 in [b76ba86](/Inori/FuckGalEngine/commit/b76ba865a636cadd8fe42be30a64419a945f9fb2)
> 
>  void* p_old_png_read_info = (void*)0x004C1650; 
> How to deal with this?

Well in old version of `MinoriPatch`, I use `bmp` format for images in `bg.paz`.
Recently I changed it to original `png` format.
If you use the compiled version of my old Chinese Patch, you just use `bmp` format as I described above.
If you want to compile the dll yourself, maybe you have to find the address yourself, since there's no history commit about this.

**Comment by imKota** [comment]
> Just place modified bmp file in a folder named `cnbg`, then run `PackCnBg.py` outside of the folder.

You will not believe it, I do: D
Watch the video:
https://take.ms/aq7mbk

**Comment by imKota** [comment]
> If you use the compiled version of my old Chinese Patch, you just use `bmp` format as I described above.

Your old compiled patch (which uses bmp) does not load cngb.paz. I downloaded the release, and it all works (translated into Chinese scripts, menus, etc.). But the modified CGs don't work.

> If you want to compile the dll yourself, maybe you have to find the address yourself, since there's no history commit about this.

Compile is not a problem, as well as correct for themselves. I don’t know how to work with a debuger. Therefore, I ask for your help in this.

**Comment by imKota** [comment]
@Inori can you write me in telegram or another real time chats?
To not flood here xD

**Comment by Inori** [comment]
> Your old compiled patch (which uses bmp) does not load cngb.paz. I downloaded the release, and it all works (translated into Chinese scripts, menus, etc.). But the modified CGs don't work.

Well I don't think so. Do you mean that my original `cnbg.paz` do not work? 

> You will not believe it, I do: D

It's the fault of your MSYS environment, use Windows cmdline instead.

**Comment by Inori** [comment]
> @Inori can you write me in telegram or another real time chats?
> To not flood here xD

I'm on my holiday of Chinese New Year, and I only have a MBP on my hand, which can not run windows programs.
Maybe I can provide you the address when I return.

**Comment by imKota** [comment]
> I'm on my holiday of Chinese New Yea


Happy New Year !
And sorry to bother you.

Thank you very much!
You really helped me out.

**Comment by Inori** [comment]
> > I'm on my holiday of Chinese New Yea
> 
> Happy New Year !
> And sorry to bother you.
> 
> > Maybe I can provide you the address when I return.
> > Thanks in advance, I will wait!
> 
> Tell me please, do you plan to do what I wrote above? Adapt the latest developments for other novels, and create branches for them.
> 
> Thank you very much!
> You really helped me out.

If you have worked out all the problems, you don't need the addresses anymore. The file name can be changed by modifying the binary content of `MinoriPatch.dll`, you can search `cnscr.paz` and change to `ruscr.paz` for example.

I do not have a plan to create branches for other games, I will only support the newest game I'm working on :) . Many addresses can be found in history commits, although it's a little complicated. :(

**Comment by imKota** [comment]
@Inori Well, I got it.
Thanks for the work you've done!

**Comment by Inori** [comment]
> @Inori Well, I got it.
> Thanks for the work you've done!

You're welcome.
