### ISSUE TITLE
XP3Viewer - missing include files

### ISSUE THREAD

**Issue by marcussacana** [Inori/FuckGalEngine#3]
i need make command line support for this tool, but here, i can't compile...
i using Visual Studio 2015 Enterprise, can you help?

![z99yvz5 1](https://cloud.githubusercontent.com/assets/10576957/9152399/ec8470ac-3dfc-11e5-8628-a567671f4247.png)

**Comment by sgqy** [comment]
The header may be a part of 'Windows Device Driver Kit'

**Comment by marcussacana** [comment]
and the my_headers.h?

**Comment by marcussacana** [comment]
i install the 'Windows Device Driver Kit' but now, i have this error
(http://i.imgur.com/hM6v4O1.png)

**Comment by Inori** [comment]
The project is not complete. You can't compile it

发自我的 Windows Phone
________________________________
发件人: marcussacana<mailto:notifications@github.com>
发送时间: ‎2015/‎8/‎9 上午 5:39
收件人: Inori/FuckGalEngine<mailto:FuckGalEngine@noreply.github.com>
主题: [FuckGalEngine] XP3Viewer - missing include files (#3)

i need make command line support for this tool, but here, i can't compile...
i using Visual Studio 2015 Enterprise, can you help?
http://i.imgur.com/Z99yVz5.png


---
Reply to this email directly or view it on GitHub:
https://github.com/Inori/FuckGalEngine/issues/3

**Comment by marcussacana** [comment]
But, this don't is the classic xp3 viewer? your after story, i know... but this?
