### ISSUE TITLE
Malie - text out for english version

### ISSUE THREAD

**Issue by masagrator** [Inori/FuckGalEngine#32]
It's possible to make script psp-malie_text_out.py work better with english version of Dies Irae game on Steam? English version is saved in unicode LE format. 

Or how to compile *.exes? I tried Visual Studio 2013 Express - error

> warning C4018: '<' : signed/unsigned mismatch	
> \Malie\DiesKit\ExecDecrypt\malie.cpp	38	1	ExecDecrypt

**Comment by 0xh3LL0** [comment]
i dont have the game, however try my build, i'm using visual studio 2017
[release.zip](https://github.com/Inori/FuckGalEngine/files/2874149/release.zip)

**Comment by masagrator** [comment]
Nothing. It doesn't show any error and nothing is created.

**Comment by 0xh3LL0** [comment]
give me the files

**Comment by masagrator** [comment]
https://drive.google.com/file/d/1MiO1n2JP0lD53yqMU0FxOYM_FNIJear6/view?usp=sharing
PC version is English Steam (patch is probably newer exec.dat)
Switch-Android is Japanese.

**Comment by 0xh3LL0** [comment]
guess you're right, i didnt works...

**Comment by Inori** [comment]
> It's possible to make script psp-malie_text_out.py work better with english version of Dies Irae game on Steam? English version is saved in unicode LE format.

I see the `exec.dat` you upload in PC folder, for this file, the entry starts at `0x3c370A` and ends at `0x411756`, if you look at its' binary content, you can find the pattern just by your eyes:

![qq 20190219160115](https://user-images.githubusercontent.com/6732524/52999246-40317a80-3460-11e9-9807-727777dcf501.jpg)

![qq 20190219160221](https://user-images.githubusercontent.com/6732524/52999268-47588880-3460-11e9-95f2-c56b8e3b6381.jpg)

Then you can modify the `psp-malie_text_out.py` script, like:
```
    start = 0x3c370A
    src.seek(start)
    end = 0x411756 -4
    count = (end-start)//8
```

After some other little error correct, eg. codec and so on, I got:
![qq 20190219155944](https://user-images.githubusercontent.com/6732524/52999500-f39a6f00-3460-11e9-8571-fa1d928fc8f4.jpg)

**Comment by masagrator** [comment]
OK, i will check that. Now it looks much cleaner. My ultimate goal is to replace english text with switch text.

**Comment by masagrator** [comment]
OK, I cleared out text that now looks like Japanese Switch version.
![image](https://user-images.githubusercontent.com/8557858/53051048-282b1c80-349b-11e9-89ed-5f24201775c4.png)
![image](https://user-images.githubusercontent.com/8557858/53051109-514bad00-349b-11e9-97f3-979b864c1222.png)
But now I need to set pspimport which have different values.
0x36a32e
0x31c450

How to find correct values?

**Comment by Inori** [comment]
> And now how to import this? pspimport doesn't work

You shouldn't expect the old code can just work directly.
Since you can export the text yourself, you know the file's binary format already.
Just replace the old text with new text, then fix the index with new offset and length.

**Comment by masagrator** [comment]
But what is the new offset? In import there are different than text_out and
I don't have PSP version to check.

śr., 20 lut 2019, 12:01 użytkownik Asuka <notifications@github.com> napisał:

**Comment by masagrator** [comment]
But what is the new offset? In import there are different than text_out and I don't have PSP version to check.

**Comment by Inori** [comment]
Read the export script's code (`psp-malie_text_out.py`), see how it works.
Once you understand the code, then you just write new text, update binary index, that's all.

**Comment by shensheng070632** [comment]
May I ask how to find the start Address?

**Comment by Monaco-a-Knox** [comment]
I'm trying to get it to work with the HD version, but psp-malie_text_out.py only creates blank files.
Could you provide a working export/import version, @Inori ? I've tried everything

Edit: nevermind, it worked using another tool.
