### ISSUE TITLE
Minori - get the cryptlibd.lib ?

### ISSUE THREAD

**Issue by IDerr** [Inori/FuckGalEngine#33]
Hi, 
I wanted to compile fuckpaz, but it needs the cryptlibd.lib file. I have compiled the library as asked, but it only generates the cryptlib.lib. 

is it a special file or it is just not needed ?

thanks

**Comment by Inori** [comment]
Here is a video on how to build it:
https://www.youtube.com/watch?v=FlHxl02YzjE

**Comment by IDerr** [comment]
Oh ok, my bad, thanks for this ;)
