### ISSUE TITLE
MinoriPatch for old games ef_first, ef_latter, ef_ft, eden

### ISSUE THREAD

**Issue by imKota** [Inori/FuckGalEngine#34]
Hello @Inori!
Now there are plans to further translate the novels, so I am about:
**ef - the first tale.
ef - the latter tale.
ef - a fairy tale of the two
eden\* / eden\* PLUS＋MOSAIC**

I hope you are free.
I think to use your skills, but again the problem with the addresses.. I don’t know them, and you didn’t work with these novels..

Could you help me with this? Or on the example of **eden\* PLUS ＋ MOSAIC** to show on the video how it happens. What would the rest I could do myself (I really hope that I can)

**Comment by imKota** [comment]
@Inori https://github.com/Ouroboros/JuusanKoubou/blob/master/Source/Hooks/eden/eden.cpp

**Comment by imKota** [comment]
@Inori, @0xh3LL0 [Hooks for eden, ef_first, ef_latter, ef_fd](https://github.com/Ouroboros/JuusanKoubou/blob/master/Source/Hooks/eden/eden.cpp)

**Comment by Inori** [comment]
Well emm..... to be honest, I haven't operated on these old games, my first targeted game is <ソレヨリノ前奏詩>, so I don't have too much information to share with you....

But since the goal is to replace text and pictures, I think it shouldn't be to much difficult.

For text, the tool `fuckpaz` can unpack and repack resource from those old games (except for Steam version though :( ), you can translate these scripts just like new ones. It's easy.

For pictures, I guess the old games also use `libpng` to parse png files, just old versions. And for `libpng`, it provides a way to custom it's io function about how to read from png data, using `png_set_read_fn`. Your goal is to find `png_read_info` in the compiled exe, hoot it and get `png_structp` pointer, then just reset io function with your own.

**Comment by imKota** [comment]
@Inori 
In any case, thanks for the information and for not ignoring:3

> except for Steam version though :(
i can send pr for `fuckpaz`

![image](https://user-images.githubusercontent.com/24241471/56655989-f7cf4c80-669c-11e9-898a-d32ddeba7cac.png)

**Comment by imKota** [comment]
@Inori And the last question. How to change the locale in exe? And then I work only Chinese fonts :((

**Comment by Inori** [comment]
Hook [`CreateFontA`](https://github.com/Inori/FuckGalEngine/blob/master/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L62) and [`CreateFontIndirectA`](https://github.com/Inori/FuckGalEngine/blob/master/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L39), change `lplf->lfCharSet`  to your location should work.

Another thing is that you may need to [modify some params](https://github.com/Inori/FuckGalEngine/blob/master/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L109) of  `EnumFontFamiliesExA`'s `lpEnumFontFamExProc` routine, to enable some special font

**Comment by imKota** [comment]
@Inori hmmm
And if you make changes to the .exe?
As you did in rendezvous_chs.exe

**Comment by Inori** [comment]
This is exactly what I said about `EnumFontFamiliesExA`, see the comments [here](https://github.com/Inori/FuckGalEngine/blob/master/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L109).

**Comment by imKota** [comment]
@Inori Thanks, I solved the problem!

Still have a question. So I want to translate the menu that opens with the right button.

![image](https://user-images.githubusercontent.com/24241471/57057959-6b80e300-6cb5-11e9-9ceb-5a17e4e2e39e.png)

I started to replace the text in the hex editor, but I faced the problem of character limit.

![image](https://user-images.githubusercontent.com/24241471/57058001-c6b2d580-6cb5-11e9-9d41-302e6830f200.png)

Is there any way around this limitation?

**Comment by imKota** [comment]
Thanks!

**Comment by imKota** [comment]
Hey, @Inori can you help me with ef fan disc?
I patched myself. I found the addresses for "pCreateFileA"
But i cannot find addresses for "pSavePngName" and "p_old png_read_info"

**Comment by imKota** [comment]
Hello, @Inori !
I found hook for [ef_first, ef_latter, ef_ft, eden](https://github.com/Ouroboros/JuusanKoubou/blob/6ce30fe951717cf64b452a4cd36a26a7b7e1ca39/Source/Hooks/eden/eden.cpp)
Can you help me with the adaptation?
