### ISSUE TITLE
Regarding minori - eden* Steam version

### ISSUE THREAD

**Issue by Mantas-B** [Inori/FuckGalEngine#37]
Hi,

I would like to retranslate the Steam version of eden* to my native language. Would that be possible if I don't have any programming knowledge? After reading through other issues I got a general idea. I successfully extracted and reinserted modified text in the original Japanese version, but fuckpaz doesn't work with the Steam version.

I believe what I need to do is find new codes for the Steam version, like the original Japanese is `"p37j344s", "ol0lOrAf", "N426Fd94", "Uyiu4Ruy"`. Please correct me if I'm wrong. I tried looking for it in Olly, but I wouldn't know where to start. So considering I'm not wrong here, how should I go about finding those codes?

Here's a test I did in the Japanese version where I changed the font symbols because they wouldn't display. Is there a better workaround?
![image](https://cdn.discordapp.com/attachments/267705754415398912/486098218854252545/unknown.png)
![image](https://cdn.discordapp.com/attachments/267705754415398912/486098726683672590/unknown.png)

**Comment by imKota** [comment]
@Mantas-B can you send me scr.paz ?

**Comment by Mantas-B** [comment]
> 
> 
> @Mantas-B can you send me scr.paz ?

https://drive.google.com/open?id=1ZVyqHDuRS6xI9trrkMr-npjbnqppkfjI

**Comment by imKota** [comment]
@Mantas-B Unfortunately, my build is not suitable. It is for the original Japanese version and English from NNL

**Comment by Inori** [comment]
You need to update [crud](https://github.com/Inori/FuckGalEngine/blob/master/Minori/Minori/fuckpaz/main.cpp#L42), [toc_key](https://github.com/Inori/FuckGalEngine/blob/master/Minori/Minori/fuckpaz/main.cpp#L27) and [dat_key](https://github.com/Inori/FuckGalEngine/blob/master/Minori/Minori/fuckpaz/main.cpp#L28).

How to find crud: [here](https://github.com/Inori/FuckGalEngine/blob/master/Minori/note.txt#L17).
How to find toc_key and dat_key: [here](https://github.com/Inori/FuckGalEngine/blob/master/Minori/get_key.osc).

**Comment by Mantas-B** [comment]
![paveikslas](https://cdn.discordapp.com/attachments/319953926319374337/567252852892762133/unknown.png) 
Hmm is this the crud?

**Comment by imKota** [comment]
@Mantas-B 

eden* steam (en)

```
   { "eden* steam (en)",
        1,
        { 
            {   "bg", {0x6F, 0xA7, 0x87, 0xC0, 0xF6, 0x0E, 0xBE, 0x2B, 0xBF, 0x25, 0x28, 0xED, 0x7D, 0x9E, 0xE9, 0x03, 0xE4, 0x2B, 0x59, 0xD8, 0x9B, 0x5E, 0x8F, 0x29, 0x90, 0x0F, 0xF0, 0x1C, 0x80, 0x3D, 0x7C, 0xF1, },
                      {0x0F, 0xF4, 0x8F, 0xD0, 0xAD, 0x9C, 0x1C, 0x30, 0x47, 0x05, 0xF1, 0x2C, 0x56, 0x03, 0xB2, 0x85, 0x06, 0xAF, 0x5F, 0x66, 0x16, 0x95, 0x1B, 0x9A, 0xCF, 0xB3, 0x64, 0x7F, 0xE2, 0xE0, 0x17, 0x7A, }
            },
            {   "bgm", {0xF4, 0x95, 0x90, 0x4B, 0x66, 0x2C, 0x30, 0xF1, 0xC7, 0x73, 0x3A, 0x09, 0x65, 0xFB, 0xF2, 0xA8, 0xCE, 0xB0, 0xA7, 0x74, 0xFE, 0xBF, 0xA1, 0x5F, 0x79, 0x23, 0x64, 0x6E, 0x2B, 0x85, 0xF5, 0x8E, },
                       {0xDB, 0x18, 0xBF, 0x08, 0x45, 0xA7, 0xC6, 0x00, 0x92, 0xE6, 0xBA, 0xA5, 0xB6, 0xA3, 0xA8, 0x2A, 0x6E, 0x16, 0x6F, 0x03, 0xF3, 0x29, 0xA3, 0x83, 0x00, 0xC0, 0xF3, 0x52, 0x21, 0x6F, 0x20, 0x3A, }
            },
            {   "scr", {0xA8, 0x6A, 0xE9, 0x83, 0x4E, 0xD5, 0x3E, 0x3A, 0x7A, 0xF5, 0xAF, 0x29, 0xD3, 0xBB, 0xEC, 0x4F, 0xB5, 0x7E, 0x71, 0x58, 0x31, 0x30, 0x66, 0x76, 0x73, 0xC2, 0x1D, 0xD4, 0x3E, 0xF0, 0xE3, 0x72, },
                       {0x92, 0x54, 0xEF, 0xB3, 0xDA, 0x3B, 0xBF, 0x1E, 0xEB, 0x96, 0xFD, 0xB8, 0x29, 0xE4, 0x40, 0x13, 0x56, 0x96, 0x4A, 0xD2, 0xF2, 0x64, 0x4F, 0xCD, 0x92, 0x3D, 0xDE, 0xC3, 0x02, 0x5E, 0x85, 0xED, }
            },
            {   "se", {0x29, 0x2B, 0x6D, 0x17, 0x47, 0x5F, 0xBC, 0x38, 0x48, 0x0E, 0x55, 0x0F, 0x96, 0xC5, 0x34, 0xE0, 0xD2, 0x1B, 0xBE, 0x16, 0xEA, 0x0D, 0xB6, 0xA5, 0x64, 0xED, 0xE8, 0x30, 0x31, 0x55, 0xB0, 0xB4, },
                      {0xB5, 0xE2, 0x58, 0xEF, 0x24, 0xC1, 0x90, 0xE2, 0xD3, 0x9E, 0x7E, 0x30, 0xB6, 0x82, 0xF8, 0xBC, 0x27, 0x24, 0xCE, 0x67, 0xD8, 0x4E, 0x10, 0x47, 0xB3, 0x4B, 0xD4, 0x98, 0x9D, 0x2E, 0x64, 0x2E, }
            },
            {   "st", {0x20, 0x88, 0xAD, 0xD9, 0x8E, 0x37, 0x26, 0x47, 0x87, 0xC3, 0x09, 0x64, 0x27, 0x0A, 0x4F, 0xAD, 0x36, 0xAF, 0x82, 0xE7, 0xAC, 0xEC, 0x76, 0xCC, 0xB6, 0x2D, 0x8D, 0x4F, 0x52, 0x74, 0x61, 0x0B, },
                      {0xAF, 0xDC, 0xF4, 0x35, 0x4D, 0xE3, 0x83, 0x56, 0xBA, 0xE3, 0xCF, 0xE6, 0xA1, 0xB2, 0x79, 0x7E, 0x43, 0x64, 0x96, 0x6D, 0x99, 0xC9, 0xCE, 0x06, 0x19, 0x4A, 0xB2, 0xF9, 0x27, 0xB5, 0x88, 0xA0, }
            },
            {   "sys", {0xA7, 0xA4, 0x42, 0xF9, 0x4D, 0xB0, 0xD7, 0xC7, 0x75, 0xD1, 0xB2, 0x48, 0x4A, 0x4E, 0x05, 0x78, 0xDB, 0x93, 0xB8, 0x1A, 0x59, 0x08, 0x9D, 0x29, 0x5E, 0x09, 0x8A, 0x3D, 0x61, 0xEE, 0x7F, 0xAB, },
                       {0x94, 0x8E, 0xD4, 0x92, 0x15, 0x0B, 0x55, 0x75, 0x43, 0xC1, 0x97, 0xE4, 0xED, 0xCB, 0xD0, 0x67, 0x49, 0x28, 0x68, 0x67, 0x10, 0xEC, 0x81, 0xB2, 0x27, 0x9C, 0x33, 0x09, 0xA8, 0x43, 0xA8, 0xBB, }
            },
            {   "voice", {0xB9, 0x2C, 0x33, 0x9F, 0x93, 0x76, 0x23, 0x55, 0x7B, 0xEE, 0x43, 0x35, 0x01, 0x19, 0x89, 0xAE, 0x1D, 0x9C, 0x0A, 0x7C, 0x73, 0x5B, 0x39, 0xB1, 0x20, 0x88, 0xA2, 0x3A, 0xB6, 0xB8, 0x2B, 0x96, },
                        {0xEA, 0x1D, 0xFD, 0x3D, 0x6F, 0x52, 0x38, 0xF7, 0x9D, 0xC5, 0x9C, 0xC8, 0x34, 0xCB, 0xB0, 0x53, 0x59, 0xDF, 0x7D, 0xD9, 0xA1, 0x72, 0xC3, 0x17, 0x6C, 0x3D, 0xCD, 0x2B, 0x86, 0xA1, 0xF1, 0xD5, }
            }, 
            {   "mov", {0x18, 0xCE, 0xFC, 0x9B, 0xC1, 0xAA, 0xCE, 0x29, 0xEC, 0xD0, 0x28, 0xB0, 0x41, 0x67, 0xDC, 0xF6, 0x60, 0xFF, 0x06, 0xF7, 0x8D, 0x00, 0x06, 0x3D, 0x0C, 0xDE, 0xDC, 0xC7, 0x03, 0x44, 0xC3, 0x67, },
                       {0xB5, 0xE2, 0x58, 0xEF, 0x24, 0xC1, 0x90, 0xE2, 0xD3, 0x9E, 0x7E, 0x30, 0xB6, 0x82, 0xF8, 0xBC, 0x27, 0x24, 0xCE, 0x67, 0xD8, 0x4E, 0x10, 0x47, 0xB3, 0x4B, 0xD4, 0x98, 0x9D, 0x2E, 0x64, 0x2E, }
            }
        },
        { "J1WaoGBi", "wCCuLx5S", "63JwEajj", "F73xvHdo" }, 
    }
```

eden* PLUS+MOSAIC steam (en)

```
    { "eden* PLUS+MOSAIC steam (en)",
        1,
        {
            {   "bg",
                { 0x38, 0x0D, 0x61, 0x9A, 0x1A, 0x22, 0x8B, 0x7A, 0x75, 0xA5, 0xBC, 0x13, 0xF3, 0xE9, 0xA1, 0x9E, 0xEF, 0xB7, 0x44, 0x83, 0x99, 0xEA, 0x11, 0xDA, 0x14, 0xED, 0xAA, 0x71, 0x97, 0x5F, 0xF6, 0x86, },
                { 0xF5, 0xD2, 0xAA, 0xF0, 0xE9, 0xD6, 0xD5, 0x50, 0x7D, 0x08, 0x26, 0x6D, 0x70, 0x90, 0xA4, 0x67, 0x7A, 0x19, 0x1E, 0x04, 0x39, 0x01, 0x2B, 0x7F, 0xE3, 0xE3, 0xFD, 0xBB, 0xDB, 0x99, 0x05, 0xD6, },
            },
            {   "bgm",
                { 0x99, 0x24, 0x1A, 0xD9, 0x33, 0xAF, 0xB0, 0xD7, 0x79, 0x5A, 0xAB, 0xAA, 0x25, 0x78, 0x6F, 0xF9, 0x95, 0xD0, 0xE7, 0xE4, 0xC2, 0xA2, 0xFC, 0x62, 0xDC, 0x84, 0xC1, 0x26, 0x59, 0x00, 0x00, 0x20, },
                { 0x7f, 0x73, 0xe1, 0x19, 0x50, 0x87, 0x36, 0x22, 0x89, 0xb0, 0xf8, 0x47, 0xb9, 0xfd, 0xb7, 0x9f, 0x65, 0x0e, 0xe5, 0x31, 0x1e, 0x00, 0x1d, 0x1b, 0xa8, 0xff, 0x1f, 0x47, 0x0f, 0x3f, 0x7d, 0x3e, },
            },
            {   "scr",
                { 0x3A, 0x49, 0xB4, 0xFF, 0xD0, 0x4F, 0xE9, 0x68, 0xB0, 0xCC, 0xAF, 0xD2, 0x7D, 0x76, 0x20, 0x2A, 0xA6, 0x5C, 0xE9, 0x99, 0xE4, 0x7C, 0xE1, 0x99, 0xA7, 0x57, 0x5D, 0x6B, 0x6E, 0xED, 0xFD, 0x83, },
                { 0xC8, 0x38, 0x0C, 0x87, 0x4A, 0xD5, 0x68, 0x97, 0x61, 0x67, 0x7A, 0xA1, 0xD9, 0x23, 0x0E, 0x90, 0x70, 0xE0, 0xD5, 0xEC, 0x61, 0xE2, 0x5D, 0x16, 0xE5, 0xE7, 0xF2, 0x9C, 0xB8, 0x88, 0xBB, 0xCD, },
            },
            {   "se",
                { 0x43, 0x19, 0x35, 0xBE, 0xC0, 0x1A, 0xBA, 0x0D, 0xA6, 0x38, 0xCE, 0x97, 0x13, 0x70, 0xED, 0x92, 0x9D, 0xB3, 0x19, 0x8A, 0x37, 0x9A, 0xAD, 0x5A, 0xF3, 0x38, 0x0D, 0x50, 0x44, 0x50, 0x14, 0xFF, },
                { 0x95, 0x3f, 0x55, 0x44, 0x8b, 0x2e, 0x7b, 0x10, 0x3f, 0x3d, 0xfa, 0x45, 0x6f, 0x94, 0x00, 0x07, 0xa7, 0x2d, 0xb8, 0x3e, 0xb2, 0xa2, 0xec, 0xd8, 0x38, 0x7a, 0xb9, 0x1a, 0xa4, 0x32, 0x35, 0x2a, },
            },
            {   "st",
                { 0xfc, 0x53, 0x32, 0xf4, 0x0b, 0xb7, 0xa1, 0x64, 0x25, 0x12, 0x49, 0x24, 0xb2, 0x31, 0x2e, 0xdc, 0x21, 0x0f, 0xbe, 0xec, 0xd4, 0x6c, 0x14, 0x42, 0x28, 0x18, 0x84, 0x57, 0xd4, 0x0d, 0x29, 0x6c, },
                { 0x0A, 0x1C, 0x87, 0x5F, 0x0C, 0x8A, 0x98, 0xFE, 0xAF, 0xBD, 0xB4, 0x99, 0x76, 0x61, 0x92, 0x3D, 0x06, 0x8F, 0x81, 0xFA, 0x69, 0x16, 0xAC, 0x8C, 0x5C, 0x78, 0x06, 0xC0, 0x90, 0xC5, 0xD3, 0xED, }
            },
            {   "sys",
                { 0xE1, 0x4E, 0x51, 0x51, 0xEA, 0x3C, 0xDE, 0x11, 0x74, 0xF6, 0x3A, 0x33, 0x5C, 0x81, 0x5D, 0x27, 0xCB, 0x99, 0x9C, 0xBF, 0xC6, 0xD9, 0x5C, 0xAB, 0xDC, 0x38, 0x9B, 0x4A, 0xF3, 0x40, 0xE7, 0x73, },
                { 0xE4, 0x46, 0x83, 0x5B, 0xFB, 0x04, 0x10, 0x59, 0x6D, 0xF5, 0x76, 0x9A, 0xBF, 0xBC, 0x07, 0x68, 0xE8, 0xC1, 0x50, 0xEF, 0x2E, 0xF8, 0x79, 0x5C, 0x21, 0x13, 0x7F, 0xDC, 0x33, 0xE9, 0xE6, 0xBA, },
            },
            {   "voice",
                { 0x28, 0x5D, 0x2A, 0x2F, 0xF7, 0x25, 0x4B, 0xDC, 0xAE, 0x0F, 0xC2, 0x2C, 0xE7, 0x3D, 0xC4, 0x4D, 0x58, 0x5C, 0xE0, 0x89, 0xE3, 0x81, 0x10, 0x3D, 0xC4, 0x03, 0xEB, 0x90, 0xD6, 0x53, 0x5D, 0x99, },
                { 0x85, 0x97, 0x40, 0xf4, 0x95, 0x48, 0x04, 0x94, 0xca, 0x8f, 0xbb, 0x71, 0xa6, 0x5f, 0xd0, 0x78, 0xe0, 0x1a, 0xcc, 0x2a, 0x21, 0xea, 0x2f, 0xf6, 0xd3, 0xd8, 0x18, 0x7b, 0x2f, 0x63, 0x94, 0xf5, },
            },
            {   "mov",
                {0x58, 0x2A, 0xC2, 0x51, 0x58, 0x15, 0xC4, 0x2D, 0xFD, 0x6F, 0x82, 0xC8, 0xD1, 0xEB, 0xC3, 0x15, 0x8F, 0x1C, 0x5B, 0xA5, 0x2C, 0xAB, 0x90, 0x05, 0x63, 0xB8, 0x1A, 0x8D, 0x44, 0x5F, 0x93, 0x82, },
                {0x09, 0xD8, 0xA5, 0x3E, 0x9B, 0xB9, 0xE7, 0xDD, 0x6D, 0x71, 0xB1, 0x55, 0xAD, 0x72, 0xF8, 0xE3, 0xDC, 0x73, 0x42, 0xDF, 0xF2, 0x8C, 0xBC, 0xDC, 0x23, 0x4D, 0x62, 0xF7, 0x76, 0x7F, 0x3D, 0x96, }
            }
        },
        { "p37j344s", "ol0lOrAf", "N426Fd94", "Uyiu4Ruy" }, 
    },
```

@Inori https://github.com/Inori/FuckGalEngine/pull/53

**Comment by Mantas-B** [comment]
Hi, does this work? I tried compiling it but ran into errors. Could you please provide a compiled version too?

**Comment by imKota** [comment]
> Hi, does this work? 

Yes. tested on eden* steam version

**Comment by Mantas-B** [comment]
How do I build fuckpaz? What VS version do I need? I built cryptpp lib with VS2019 and tried building fuckpaz with both VS2019 and VS2017, but always get errors. I referenced this video https://www.youtube.com/watch?v=FlHxl02YzjE from another issue in this repository.

**Comment by imKota** [comment]
@Mantas-B do you have telegram?

**Comment by imKota** [comment]
@Mantas-B compiled version [fuckpaz.zip](https://github.com/Inori/FuckGalEngine/files/7465338/fuckpaz.zip)

**Comment by Mantas-B** [comment]
It works! Thank you so much!! :)

**Comment by Cosetto** [comment]
> @Mantas-B compiled version [fuckpaz.zip](https://github.com/Inori/FuckGalEngine/files/7465338/fuckpaz.zip)

Does this include repack into .paz again?

**Comment by imKota** [comment]
> > @Mantas-B compiled version [fuckpaz.zip](https://github.com/Inori/FuckGalEngine/files/7465338/fuckpaz.zip)
> 
> Does this include repack into .paz again?

Read help...
![image](https://user-images.githubusercontent.com/24241471/140326246-fea1fc30-21a0-4539-accd-ddd25a7edd11.png)

**Comment by Cosetto** [comment]
> > > @Mantas-B compiled version [fuckpaz.zip](https://github.com/Inori/FuckGalEngine/files/7465338/fuckpaz.zip)
> > 
> > 
> > Does this include repack into .paz again?
> 
> Read help... ![image](https://user-images.githubusercontent.com/24241471/140326246-fea1fc30-21a0-4539-accd-ddd25a7edd11.png)

Thanks. I want to ask the sc_text_out.py works with Eden English? It gave me blank script 
![image](https://user-images.githubusercontent.com/81801486/140332603-203f90a6-69f8-47d6-9d47-0472f3489bf9.png)

**Comment by Mantas-B** [comment]
You can edit the .sc file directly. I use Notepad++

**Comment by Cosetto** [comment]
> You can edit the .sc file directly. I use Notepad++

I know but it would be nice to get the text without mixing other thing

**Comment by OtameganeMinh** [comment]
> @Mantas-B compiled version [fuckpaz.zip](https://github.com/Inori/FuckGalEngine/files/7465338/fuckpaz.zip)

I'm trying to translate ef - first tale steam version but your compiled version doesn't have it. Can you update it? Thanks in advance!

**Comment by imKota** [comment]
> I'm trying to translate ef - first tale steam version but your compiled version doesn't have it. Can you update it? Thanks in advance!

@OtameganeMinh please upload **ef - first tale steam version** on doodle drive or mega

**Comment by OtameganeMinh** [comment]
@imKota You mean the executable and scr.paz files? Here it is
https://drive.google.com/file/d/18jRb5YaJgZmwjpC0_GGdjEfZa1fBy_iD/view?usp=sharing

**Comment by imKota** [comment]
@OtameganeMinh done, check PR

**Comment by OtameganeMinh** [comment]
@imKota Can you send me the compiled version. I can't compile it, i'm using VS2017. Thank you so much for your help!

**Comment by imKota** [comment]
> @imKota Can you send me the compiled version. I can't compile it, i'm using VS2017. Thank you so much for your help!

https://github.com/imKota/fuckpaz

**Comment by Berthog** [comment]
@imKota 
Sorry the mention here, do you know if this engine allows to create an update patch instead of repacking all the package (including the non-edited files)

**Comment by imKota** [comment]
> @imKota Sorry the mention here, do you know if this engine allows to create an update patch instead of repacking all the package (including the non-edited files)

Nope
