### ISSUE TITLE
Minori (Natsuzora no Perseus)

### ISSUE THREAD

**Issue by imKota** [Inori/FuckGalEngine#38]
Hello @Inori !
Can you help me with the addresses for "Natsuzora no Perseus"? 
I tried it, I sort of find it, but as I understand it, they still don’t fit for **pCreateFileA** and **pCreateFileARetn**. 

```
01027CBC | FF15 CC910F01             | call dword ptr ds:[<&CreateFileA>]                  |
01027CC2 | 8BF0                      | mov esi,eax                                         |

PVOID pCreateFileA = (PVOID)0x01027CBC;
PVOID pCreateFileARetn = (PVOID)0x01027CC2;


010290FE | FF15 44011701             | call dword ptr ds:[<&CreateFileA>]                  |
01029104 | 8BF8                      | mov edi,eax                                         | eax:sub_1097000

PVOID pCreateFileA = (PVOID)0x010290FE;
PVOID pCreateFileARetn = (PVOID)0x01029104;

```

I could not find addresses for these at all.
```
void *pSavePngName = (void*)0x???????;
void* p_old_png_read_info = (void*)0x???????;

```
For the rest of the game I found everything. And everyone works. But to this one, well, it doesn’t take any chances..

**Comment by Inori** [comment]
First, you need to modity the exe file to [disable ASLR](https://github.com/Inori/FuckGalEngine/blob/master/Minori/exe_crack.txt#L3)

Second, the latest code matches Minori's last game: Sonokemo, you can download this game for reference, then I think it will be easy for you to find these address.

Also, almost all hard code address have comments about how to find it. 
Such as [`pCreateFileA` and it's return address](https://github.com/Inori/FuckGalEngine/blob/master/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L166)
[`pSavePngName`](https://github.com/Inori/FuckGalEngine/blob/master/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L525)

**Comment by imKota** [comment]
@Inori Hmm, okay i tray today.

**Comment by Inori** [comment]
Sorry,  the latest code matches Minori's game:Trinoline

**Comment by imKota** [comment]
@Inori There is one more question But according to another engine. I will write here. 
https://github.com/Inori/FuckGalEngine/tree/master/QLIE
We are also engaged in the translation of "Koiken Otome"
I was able to unpack resources, but with the packaging problem. Maybe you have any developments on QLIE. In particular, repacking archives version FilePackVer3.0

**Comment by imKota** [comment]
@Inori Thanks!
I solved the problem. It turns out that was pretty easy.

But still I am very interested. How to deal with these games? There, as I understand the structure is different. https://github.com/Inori/FuckGalEngine/issues/34
