### ISSUE TITLE
QLIE repack problem

### ISSUE THREAD

**Issue by Inori** [Inori/FuckGalEngine#39]
@Inori There is one more question But according to another engine. I will write here. 
https://github.com/Inori/FuckGalEngine/tree/master/QLIE
We are also engaged in the translation of "Koiken Otome"
I was able to unpack resources, but with the packaging problem. Maybe you have any developments on QLIE. In particular, repacking archives version FilePackVer3.0

_Originally posted by @imKota in https://github.com/Inori/FuckGalEngine/issues/38#issuecomment-484499800_

**Comment by imKota** [comment]
I somehow was able to unpack resources. With saving directories and file structure. But the files themselves are not read. Packed with this toolkit.
https://github.com/Ouroboros/JuusanKoubou/tree/master/Source/Tools/CSharp/Packer

**Comment by imKota** [comment]
@Inori I somehow was able to unpack resources. With saving directories and file structure. But the files themselves are not read. Packed with this toolkit.
https://github.com/Ouroboros/JuusanKoubou/tree/master/Source/Tools/CSharp/Packer

**Comment by Inori** [comment]
Let's open a new issue.
For QLIE engine, there's no need to repack the resources.
The engine can read from the unpacked file, as override of the packed one.
But you need to modify the exe a little.
I don't remember how to modify the exe anymore because it's long time ago since I last play with this engine.
You can do some binary compare between the two exe [in this package](https://github.com/Inori/FuckGalEngine/blob/master/QLIE/%E4%B8%87%E5%8D%8E%E9%95%9C3%E5%8F%82%E8%80%83%E8%B5%84%E6%BA%90.7z)

After all of that, you can pack the modified exe and resource files using some tools like MoleBox or [enigmavb](https://github.com/Inori/FuckGalEngine/blob/master/_general_tools/enigmavb.exe)

**Comment by imKota** [comment]
@Inori Look at that https://take.ms/unet8 
WTD ? xDD

> For QLIE engine, there's no need to repack the resources.
The engine can read from the unpacked file, as override of the packed one.
But you need to modify the exe a little.
I don't remember how to modify the exe anymore because it's long time ago since I last play with this engine.
You can do some binary compare between the two exe in this package

Didn't know it. Today I will see what you have there

> After all of that, you can pack the modified exe and resource files using some tools like MoleBox or enigmavb

But this is already interesting!

**Comment by sasoriakasuna** [comment]
Can you make a tutorial how to do it?  

> For QLIE engine, there's no need to repack the resources.
The engine can read from the unpacked file, as override of the packed one.
But you need to modify the exe a little.

Literally you will help a lot of Fan translation community, BTW we are working on princess lover! VN to be honest i did not understand anything on the package you post,
> You can do some binary compare between the two exe in this package

 i really want to know how to edit an exe on ollydbg. But i did not really have the bases, ;_; i only know how to speak Anime.

The tool posted barely have instructions, we dont know how to use it :/ not command line help ✌️

**Comment by imKota** [comment]
@sasoriakasuna Hello! 
I solved the problem with repacking. 
Do you have a discord? Or any other realtime chat?

**Comment by sasoriakasuna** [comment]
Yeah! Please tell me how to do it. My discord is @MichaelK#9472

**Comment by imKota** [comment]
@sasoriakasuna I've sent a request :3

**Comment by kazurabakouta** [comment]
@imKota Hey, can I add you? I need your solution on repacking qlie archive as a reference. Thanks.

**Comment by imKota** [comment]
> @imKota Hey, can I add you? I need your solution on repacking qlie archive as a reference. Thanks.
> 
> 

Kota#1914

**Comment by liqueurs** [comment]
> > @imKota嘿，我可以加你吗？我需要您重新包装qlie存档的解决方案作为参考。谢谢。
> 
> 亚庇＃1914

Hello, I need a copy for reference. Can you share it?

**Comment by liqueurs** [comment]
> > @imKota Hey, can I add you? I need your solution on repacking qlie archive as a reference. Thanks.
> 
> Kota#1914

Hello, I need a copy for reference. Can you share it?

**Comment by imKota** [comment]
@liqueurs https://github.com/imKota/qliepack
