### ISSUE TITLE
IGPatch vertical font fix

### ISSUE THREAD

**Issue by imKota** [Inori/FuckGalEngine#41]
Hello, @Inori 
Can you tell me how you can change the vertical orientation of the text to horizontal?
https://github.com/Inori/FuckGalEngine/tree/master/InnocentGrey/IGKit/IGPatch
![image](https://user-images.githubusercontent.com/24241471/60565930-048fb100-9d6e-11e9-9c14-19c50ff2f02b.png)

**Comment by BillStark001** [comment]
I had not modified the direction of the text, but IG's all displayments depend on scripts parsed by the engine. You may parse the scripts using https://github.com/lennylxx/IG_tools. The repo doesn't directly provide a parser still it consists of the analysis of the format.

**Comment by imKota** [comment]
@BillStark001 The scripts are nothing but text. Also in debug mode
![image](https://user-images.githubusercontent.com/24241471/60576038-49731200-9d85-11e9-8433-545f50c123dc.png)

**Comment by BillStark001** [comment]
Scripts are not only text, those hex codes within the text are controllers. 
btw. this h scene is exhilarating:D

**Comment by imKota** [comment]
@BillStark001 Maybe you have ideas how to fix?

**Comment by BillStark001** [comment]
Yep, each 4-hex-code-group(maybe longer) is a control statement, e. g. 0822 0100 0000 0500 bgm04 and 0400 3000 [talks]. You can open several script files (in both horizontal and vertical text direction) in debug mode and compare them to find any differences. 
I believe the control statement of text direction switching is 04B6 0001. It appears in file as 00 B6 04 01 and appears pairly for the first time it switches the directon to vertical and the second time horizontal. I've tested my ideas on FLOWERS. 
You may delete those statements and the text will be horizontal.

**Comment by imKota** [comment]
@BillStark001 Then can I be insolent, and ask you to make an edit to the unpacker? 
I'm not good at c ++...

**Comment by BillStark001** [comment]
I'm sorry, I'm busying with university application....

**Comment by imKota** [comment]
@BillStark001 How will you be free))

**Comment by BillStark001** [comment]
maybe the next April......

**Comment by imKota** [comment]
> I've tested my ideas on FLOWERS.

And how did you test?

**Comment by imKota** [comment]
@BillStark001 
> I've tested my ideas on FLOWERS.

And how did you test?

**Comment by BillStark001** [comment]
Theoretically just open the file with a hex editor like 010 Editor, search 00 B6 04 01, 00 B6 04 00 and remove them.
However, IG used a simple encoding after CureGirl. The encoding way is to minus the original bit from 255(0xFF) for each bit, so you should remove FF 49 FB FE and FF 49 FB FF.

**Comment by imKota** [comment]
@BillStark001 Removed from the first file (FF 49 FB FF), where the vertical text.
FF 49 FB FE was not found.
All text is still vertical.

**Comment by BillStark001** [comment]
Well...what is the game's name? I'll try to fix it at my leisure.

**Comment by imKota** [comment]
@BillStark001 [Ame Koi](https://vndb.org/v15426)

**Comment by imKota** [comment]
Scripts are unpacked only this way: igscript -x -p name.x name.txt

**Comment by imKota** [comment]
dl [link](https://mega.nz/#!cB8DBSyT!EacRGdjfqs6j8n3vH7pvrdR9hkJ6-B-0zMxSjhIuO4Q)

**Comment by imKota** [comment]
@BillStark001 I was able to figure it out. Now another problem..

Test message en/ru
`Test. EN - ok. Тест. RU - ok.`

![image](https://user-images.githubusercontent.com/24241471/60587602-8945f380-9d9d-11e9-9bf4-df44190c0c6d.png)

it's (RUSSIAN_CHARSET, ANSI_CHARSET, DEFAULT_CHARSET)
![image](https://user-images.githubusercontent.com/24241471/60587640-a11d7780-9d9d-11e9-816f-c71990eaf30c.png)

**Comment by BillStark001** [comment]
Seems like your charset in the apis are correct, but you're still editing the texts in Shift-JIS charset.

**Comment by imKota** [comment]
@BillStark001 i try utf8..

**Comment by BillStark001** [comment]
The charsets of text file and dll should be the same, and since you've assigned the arguments to RUSSIAN_CHARSET, you'd better save in RUSSIAN_CHARSET(both utf8 is also ok, but it may be a little larger).

**Comment by imKota** [comment]
@BillStark001 hello!
I try: 
```
dll (RUSSIAN_CHARSET) + text ani/utf8,
dll (ANSI_CHARSET) + text ani/utf8, 
dll (DEFAULT_CHARSET) + text ani/utf8
```
in another japanese vn from 'minori', i use:
```
	lpLogfont->lfCharSet = ANSI_CHARSET;
	lpLogfont->lfFaceName[0] = '\1';
```
and text in encoding shift-jis, and it's work
![image](https://user-images.githubusercontent.com/24241471/60675041-2bd8a200-9e84-11e9-9cc2-790b86a6e44c.png)

**Comment by BillStark001** [comment]
wow, congratulations :D

**Comment by imKota** [comment]
@BillStark001 but on "ame koi" not work:DDD

**Comment by Inori** [comment]
The direction of the rendered font is controled by the [`@` char](https://github.com/Inori/FuckGalEngine/blob/master/InnocentGrey/IGKit/IGPatch/IGPatch.cpp#L44) before font name.

**Comment by imKota** [comment]
@Inori hi!
With the direction of the text figured out. 
Can you help with the conclusion of the Russian language?
![image](https://user-images.githubusercontent.com/24241471/60764219-2c448900-a08e-11e9-948c-1203e3731e1e.png)

**Comment by imKota** [comment]
@Inori 
> The direction of the rendered font is controled by the [`@` char](https://github.com/Inori/FuckGalEngine/blob/master/InnocentGrey/IGKit/IGPatch/IGPatch.cpp#L44) before font name.

And, this method not working :(
I try:

![image](https://user-images.githubusercontent.com/24241471/60764292-a9243280-a08f-11e9-92ce-3443e7660e90.png)

and result:

![image](https://user-images.githubusercontent.com/24241471/60764298-ba6d3f00-a08f-11e9-9888-d0bb10449882.png)

direction dint changes

![image](https://user-images.githubusercontent.com/24241471/60764324-08824280-a090-11e9-958b-37c164b1dbc3.png)

**Comment by Inori** [comment]
Maybe you should have a look at this:
https://github.com/Inori/FuckGalEngine/blob/master/InnocentGrey/IGKit/IGPatch/IGPatch.cpp#L109

**Comment by imKota** [comment]
> Maybe you should have a look at this:
> https://github.com/Inori/FuckGalEngine/blob/master/InnocentGrey/IGKit/IGPatch/IGPatch.cpp#L109

i edit this (russian, english, japanese)..

**Comment by Inori** [comment]
well...I remember I just changed the country name and add a `@` in front of the font name, then I got correct text rendering.

**Comment by imKota** [comment]
@Inori 
> well...I remember I just changed the country name and add a `@` in front of the font name, then I got correct text rendering.

Strange..

**Comment by imKota** [comment]
@Inori 
While you are here, you can look this https://github.com/Inori/FuckGalEngine/issues/34#issuecomment-505683584

**Comment by vnlovers** [comment]
<img width="174" alt="innocent" src="https://user-images.githubusercontent.com/43198042/65727310-9135db00-e0e1-11e9-9457-d13d7c42ebc7.png">
Sorry for interrrupting. But I want to ask, why I get this error?

**Comment by Tfausx** [comment]
Hi @Inori  , i re-opened this topic just to ask about generating the .dll of the font, i don't get the part of the modification to create that dll, i mean:
---------
	if (!wcscmp(lplf->lfFaceName, L"@ＭＳ 明朝"))
	{
		wcscpy(lplf->lfFaceName, L"@黑体");
	}
	else if (!wcscmp(lplf->lfFaceName, L"ＭＳ 明朝"))
	{
		wcscpy(lplf->lfFaceName, L"黑体");
	}
	else if (!wcscmp(lplf->lfFaceName, L"ＭＳ ゴシック"))
	{
		wcscpy(lplf->lfFaceName, L"黑体");
---------
In this part i just only need to change the first line? Like:

	if (!wcscmp(lplf->lfFaceName, L"@My modified font"))
---------
I did that, generate the dll, put in on the plugin folder but the game doesn't recognize the new font, i tested with the latest Flowers game and Kara no Shoujo the last episode! If is not a problem for you, can give me a little more detailed explanation about the font change?

Thanks in advance!
