### ISSUE TITLE
Have no idea about finding minori dat_key

### ISSUE THREAD

**Issue by Gezine** [Inori/FuckGalEngine#47]
I'm trying to find keys for eden* steam version

I used your ollydbg script to find toc_key
but I have no clue about finding dat_key

any advice?

	{ "eden* steam",
	1,
	{ { "bg", { 0x6F, 0xA7, 0x87, 0xC0, 0xF6, 0x0E, 0xBE, 0x2B, 0xBF, 0x25, 0x28, 0xED, 0x7D, 0x9E, 0xE9, 0x03, 0xE4, 0x2B, 0x59, 0xD8, 0x9B, 0x5E, 0x8F, 0x29, 0x90, 0x0F, 0xF0, 0x1C, 0x80, 0x3D, 0x7C, 0xF1, },
	{ } },
	{ "bgm", { 0xF4, 0x95, 0x90, 0x4B, 0x66, 0x2C, 0x30, 0xF1, 0xC7, 0x73, 0x3A, 0x09, 0x65, 0xFB, 0xF2, 0xA8, 0xCE, 0xB0, 0xA7, 0x74, 0xFE, 0xBF, 0xA1, 0x5F, 0x79, 0x23, 0x64, 0x6E, 0x2B, 0x85, 0xF5, 0x8E, },
	{  } },
	{ "mov", { 0x18, 0xCE, 0xFC, 0x9B, 0xC1, 0xAA, 0xCE, 0x29, 0xEC, 0xD0, 0x28, 0xB0, 0x41, 0x67, 0xDC, 0xF6, 0x60, 0xFF, 0x06, 0xF7, 0x8D, 0x00, 0x06, 0x3D, 0x0C, 0xDE, 0xDC, 0xC7, 0x03, 0x44, 0xC3, 0x67, },
	{ 0 }, },
	{ "scr", { 0xA8, 0x6A, 0xE9, 0x83, 0x4E, 0xD5, 0x3E, 0x3A, 0x7A, 0xF5, 0xAF, 0x29, 0xD3, 0xBB, 0xEC, 0x4F, 0xB5, 0x7E, 0x71, 0x58, 0x31, 0x30, 0x66, 0x76, 0x73, 0xC2, 0x1D, 0xD4, 0x3E, 0xF0, 0xE3, 0x72, },
	{ } },
	{ "se", { 0x29, 0x2B, 0x6D, 0x17, 0x47, 0x5F, 0xBC, 0x38, 0x48, 0x0E, 0x55, 0x0F, 0x96, 0xC5, 0x34, 0xE0, 0xD2, 0x1B, 0xBE, 0x16, 0xEA, 0x0D, 0xB6, 0xA5, 0x64, 0xED, 0xE8, 0x30, 0x31, 0x55, 0xB0, 0xB4, },
	{ } },
	{ "sys", { 0xA7, 0xA4, 0x42, 0xF9, 0x4D, 0xB0, 0xD7, 0xC7, 0x75, 0xD1, 0xB2, 0x48, 0x4A, 0x4E, 0x05, 0x78, 0xDB, 0x93, 0xB8, 0x1A, 0x59, 0x08, 0x9D, 0x29, 0x5E, 0x09, 0x8A, 0x3D, 0x61, 0xEE, 0x7F, 0xAB, },
	{} },
	{ "voice", { 0xB9, 0x2C, 0x33, 0x9F, 0x93, 0x76, 0x23, 0x55, 0x7B, 0xEE, 0x43, 0x35, 0x01, 0x19, 0x89, 0xAE, 0x1D, 0x9C, 0x0A, 0x7C, 0x73, 0x5B, 0x39, 0xB1, 0x20, 0x88, 0xA2, 0x3A, 0xB6, 0xB8, 0x2B, 0x96, },
	{ } }, },
	{ "63JwEajj", "wCCuLx5S", "J1WaoGBi", "F73xvHdo" }, },

**Comment by Gezine** [comment]
This is exe of eden steam

[eden_en.zip](https://github.com/Inori/FuckGalEngine/files/4495000/eden_en.zip)

**Comment by Mantas-B** [comment]
Check #37 and be sure to share if you succeed

**Comment by Gezine** [comment]
> Check #37 and be sure to share if you succeed

Actually I followed Inori's instruction in that thread.
And got toc_key but no go for dat_key =(

his get_key.osc script does not work properly on steam eden.
only toc_key.osc worked.

**Comment by imKota** [comment]
@Gezine hello
> And got toc_key but no go for dat_key =(

Did you find KeyFunction call address for get_key.osc ?
https://github.com/Inori/FuckGalEngine/blob/master/Minori/get_key.osc#L18-L27

**Comment by imKota** [comment]
@Gezine https://github.com/Inori/FuckGalEngine/issues/37#issuecomment-957325861

**Comment by imKota** [comment]
@Inori you can close this issue
