### ISSUE TITLE
ahdprc 导入汉化文本的问题

### ISSUE THREAD

**Issue by Zmrn** [Inori/FuckGalEngine#49]
为了汉化看星星IF《見上げてごらん、夜空の星を Interstellar Focus》，我用nodejs写了一个文本替换的脚本。替换后的ws2文件加密打包后放回游戏，看似运行良好，但是会出现许多玄学问题。

例如第一个ws2文件结尾播放了游戏OP，但是OP无法跳过，结束后白屏不载入下一个脚本。或是OP无限循环。我试着把第二个ws2文件的名字改成第一个的，甚至会出现游戏全程默认快进无法停止的问题。

我以为是ws2文件中有些重要的偏移数据需要修改，后来找到了ahdprc（我没能成功编译，于是下载了其他人编译后的文件）。结果使用ahdprc ws2替换后的ws2文件也有一样的问题，而且似乎ahdprc也只是单纯的替换文本，并没有修改其他的地方？

其他advHD的游戏也有这样的问题吗？还是只有《見上げてごらん、夜空の星を Interstellar Focus》是这样的？大佬们能不能告诉我我应该怎么做才好？

**Comment by Zmrn** [comment]
![00](https://user-images.githubusercontent.com/16983764/81220347-bdb8ba80-9013-11ea-889a-b5bc54276813.jpg)
在进行到OP之前一切都很顺利

**Comment by Inori** [comment]
这个rep我已经基本不维护了，ahdprc是 @sgqy 写的，可以问问他

**Comment by sgqy** [comment]
远古工具没有考虑到address的问题
文本替换后长度就变了，其余offset相关信息直接炸
建议使用外挂的方式：https://github.com/Inori/FuckGalEngine/tree/master/AdvHD/dynamic

**Comment by Zmrn** [comment]
原来这里就有钩API的程序……我研究了好久才写出来了个DLL解决了。还是谢谢各位大佬抽出时间回复我。
