### ISSUE TITLE
AdvHD - how to modify Willplus image setting

### ISSUE THREAD

**Issue by mireado** [Inori/FuckGalEngine#6]
I'm going to localization some willplus game using 'Ahdprc'.
http://imgur.com/rLgDBmQ

but, I have problem on repacking pna file.
It seem to be work only image have same size with file '_cht.bin'.

So, Is someway to modify '_cht.bin' file OR change png file size to match with '_cht.bin'?
Thank you for reading >_<

**Comment by sgqy** [comment]
I remember that image info such as width and height should not be modified, only except file size, which is tested....
Because there are too much unknown info in pna header....

**Comment by mireado** [comment]
Thank you for answer >_<
and sorry to late..

I was find file size on header file >_<
they using unsigned short for size

![img]http://i.imgur.com/EnjtDb6.png[/img]
red : file numbering(and pna header)
blue : width and height
green : size (byte)

but I still not understand violet.

**Comment by sgqy** [comment]
values in violet MAYBE some info about image layout or other attributes...
I do not understand them too. xD
so I designed not modifying them, and not modifying image count
