### ISSUE TITLE
FuckGalEngine-master\Silky\AkbTool \png.h is missing

### ISSUE THREAD

**Issue by wjh191** [Inori/FuckGalEngine#60]

**Comment by Cosetto** [comment]
https://github.com/crskycode/GSIWinNewTools/tree/master/AKBTool
This one can only create .AKB, use GARbro to convert .AKB to .png

**Comment by Cosetto** [comment]
You need to extract .metadata.json from .AKB with the tool in order to create new .akb, or you can use original settings of the png

**Comment by imKota** [comment]
@wjh191 
[AkbTool.zip](https://github.com/Inori/FuckGalEngine/files/10499104/AkbTool.zip)
