### ISSUE TITLE
ExHIBIT How To Get Key

### ISSUE THREAD

**Issue by hentaitaku** [Inori/FuckGalEngine#61]
Hi how can i make find the key for ExHIBIT rld file?
Just know that you need to debug game exe with rld_decrypt but what should i copy from there.
Hope to get some help.

**Comment by Cosetto** [comment]
https://github.com/amayra/arc_conv 
![image](https://user-images.githubusercontent.com/81801486/227099397-78b0c8ac-fc56-4e05-a5dd-288bc6656203.png)
arc_conv.exe --mod exhibit key 00001.rld key.txt

**Comment by Cosetto** [comment]
Close issue time?
