### ISSUE TITLE
How to pick the .ws2 file using ahdprc's command line

### ISSUE THREAD

**Issue by 0Chiroptera** [Inori/FuckGalEngine#7]
关于这条命令:
`ws2: (提取) ahdprc ws2 -i IN  -t TXTO -b BINO`
不是很清楚`-b  指定作为二进制的文件`这个参数是怎么用的...

我在提取的时候指定到解包pna时生成的某个 _cht.bin(45.1 KB),遇到的问题是提取出的文本也只有50.5 KB, 为此想来请教一下使用这条提取命令的正确方法和步骤...=-=

此外还有个小问题, advhd脚本中有没有组合各种差分立绘时需要依据的坐标? 合成立绘的时候不知道五官该放哪了..

**Comment by sgqy** [comment]
`-b`是用来保存文本出现位置的，用于之后的封装。
推荐拆包使用'/AdvHD/ws2.cpp'
封包https://github.com/marcussacana/WillPlusManager
封包会有一些问题（#5）
立绘这个参数没研究过。不过坐标在pna文件里（#6）。
以前用这个坐标强行拼图，结果人物脸的颜色不太对。\_(:з」∠)\_

**Comment by 0Chiroptera** [comment]
谢谢ww 待会去研究一下ws2.cpp 和pna
其实用ahdprc一个一个拆ws2是可以成功提取的,但是一旦批处理就会出现我说的问题了orz

**Comment by 0Chiroptera** [comment]
唔再打扰一下,我用hex editor打开_cht.bin,结果没在里面找到坐标, #6的方法没看懂.

**Comment by sgqy** [comment]
http://asmodean.reverse.net/pages/exoozoarc.html
asmodean的工具里给出了相关信息

**Comment by 0Chiroptera** [comment]
知道了,感谢帮助:)
