### ISSUE TITLE
How to use PJADV TextTool ?

### ISSUE THREAD

**Issue by Neroldy** [Inori/FuckGalEngine#9]
哪位大大能解释一下PJADV中的那个夏の終わりのニルヴァーナ中的TextTool应该怎么使用？我研究了好久都不会。。。非常感谢！

Can someone tell me how to use the PJADV TextTool?
Thanks ~

**Comment by sgqy** [comment]
在「添加/删除程序」里，为你的 Visual Studio（2008 及以上版本）添加Microsoft Foundation Classes（MFC）功能。

在系统为中文代码页环境下，打开 TextTool.sln，使用 VS 的构建功能（快捷键应该为 Ctrl+Shift+B）编译生成项目。

编译成功之后，按 Ctrl+F5 键执行这个程序。

若有其他问题请回复 (*・∀-)~

**Comment by Neroldy** [comment]
@sgqy 嗯，感谢回复。编译我已经通过了，只是不知道这个工具怎么用而已。不知道是否有手册什么的？

**Comment by sgqy** [comment]
我这里是对 scenario.dat 执行 2 次 加密/解密 后可读取。
不知相同引擎的其他引擎会如何工作。

**Comment by Neroldy** [comment]
@sgqy 不知道大大能否给出几个简单的步骤图？主要是我看到界面上既有读入文件，又有读取这样的按钮，不知道是读入哪个文件？是读入scenario.dat，还是读入textdata.bin，还是读入解密后的textdata.bin.out？
我的感觉是这个加密/解密是对于textdata.bin进行异或操作的。谢谢！

**Comment by Neroldy** [comment]
@sgqy 感谢大大，我会用了。:)

**Comment by Neroldy** [comment]
还有一个问题，就是这个工具每次写出文件的时候都是在textdata.bin后面append新的文本？感觉几轮写出下来，textdata.bin越来越大。。。还是我的使用姿势不对？谢谢！

**Comment by Neroldy** [comment]
@sgqy 大大，我有个问题想要请教，但是苦于不知道如何联系，只好在这里打扰了，就是大大知道怎么将资源，dll以及exe程序打包成一个单独文件吗？运行的时候再释放到内存。软件我找到好用的就是Engima，但是好像有点问题，所以想问一下是否有些代码或者其他好用的工具？谢谢！

**Comment by sgqy** [comment]
可以试试mbox2w
另打包似乎没必要吧（

**Comment by Neroldy** [comment]
@sgqy 打包也是不想把资源文件暴露出来，另外mbox2w是指MoleBox Pro吗？谢谢！

**Comment by sgqy** [comment]
是这个。
